# Generated by Django 2.0.5 on 2019-08-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_token',
            field=models.CharField(default='', max_length=900),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='spotify_id',
            field=models.CharField(default='', max_length=900),
        ),
    ]
